# Generated by Django 3.2.11 on 2022-01-16 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShortSummary',
        ),
    ]
