# Generated by Django 3.2.11 on 2022-01-16 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_delete_shortsummary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
