# Generated by Django 3.2.11 on 2022-01-16 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
