# Generated by Django 3.2.11 on 2022-01-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_feedbackmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmodel',
            name='post_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
