# Generated by Django 3.2.11 on 2022-02-23 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_feedbackmodel_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmodel',
            name='post_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 23, 13, 23, 59, 754554)),
        ),
    ]
