# Generated by Django 3.2.11 on 2022-02-23 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0011_alter_feedbackmodel_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmodel',
            name='post_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 23, 14, 33, 22, 428958)),
        ),
    ]
